### ISSUE TITLE
Food UI Images

### ISSUE THREAD

**Issue by Mashood97** [Mashood97/flutter_food_ui_practice#1]
![ui2](https://user-images.githubusercontent.com/40804440/78467168-32ea5480-7723-11ea-9646-5123b8b9607b.png)
![ui3](https://user-images.githubusercontent.com/40804440/78467171-35e54500-7723-11ea-8f64-2a744c3cc38d.png)
![ui4](https://user-images.githubusercontent.com/40804440/78467173-38e03580-7723-11ea-8f0b-b290baed9f94.png)
![ui5](https://user-images.githubusercontent.com/40804440/78467174-3bdb2600-7723-11ea-921b-d57c3ecba437.png)
![ui](https://user-images.githubusercontent.com/40804440/78467175-3da4e980-7723-11ea-8c3f-5cd591ad7b2a.png)

**Comment by alikarani** [comment]
@Mashood97 please add details to this Issue, So that I could fix it and create a merge request for it.
